services:
  bot:
    container_name: CMoD_CircleManagerOnDiscord
    build: .
    volumes:
      - ./bot:/usr/src/app:rw
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - GUILDS=${GUILDS}
      - CREDENTIALS_FILE=${CREDENTIALS_FILE}
      - CALENDAR_ID=${CALENDAR_ID}
    command: ["python", "main.py"]
    tty: true